<?php // this is an autogenerated file - do not edit (created Tue, 04 Oct 2011 00:39:46 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'theseer\\tools\\abstractproperties' => '/src/AbstractProperties.php',
            'theseer\\tools\\abstractstream' => '/src/AbstractStream.php',
            'theseer\\tools\\languagestream' => '/src/LanguageStream.php',
            'theseer\\tools\\propertiesexception' => '/src/AbstractProperties.php',
            'theseer\\tools\\simplestream' => '/src/SimpleStream.php',
            'theseer\\tools\\streamexception' => '/src/AbstractStream.php',
            'theseer\\tools\\streammanager' => '/src/StreamManager.php',
            'theseer\\tools\\streammanagerexception' => '/src/StreamManager.php',
            'theseer\\tools\\streamproperties' => '/src/StreamProperties.php',
            'theseer\\tools\\streamuri' => '/src/StreamUri.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
